### ISSUE TITLE
Suggestion: Option to show/hide folders seperately from files

### ISSUE THREAD

**Issue by emveeoh** [ssorallen/no-file-icons#2]
Just a suggestion... 
It would be awesome if I had the option to choose between hiding file icons, folder icons or both. As it is now, all file and folder icons are hidden. I _hate_ folder icons, but I _love_ file icons and want to see them. It would be nice if I could have seperate checkbox options for each type of icon. Thank you! 

If it helps, I was able to hide just the folders from my own stylesheet with this css:

``` css
   .project-root.selected::before {
    // hide icon at root
     display:          none;
   }

   .project-root .header ::before {
    // hide folder icon at root
     content:          none;
   }

 .list-tree.has-collapsable-children > .list-nested-item > .list-item::before,
 .list-tree.has-collapsable-children >.list-nested-item.collapsed > .list-item::before {
  // Disable arrow and icon on project root bar
   content:            none;
 }
```
